### PR TITLE
Introduce possibility to use different renderers

### PR DESCRIPTION
**Pull request by pdalpra**
Currently, sbt-buildinfo only allows to write the build info in the form of a Scala class.
It could, however, be interesting to allow to dump the build in another format, e.g. JSON.
This PR introduces `BuildInfoRenderer` (along with a few other data types), a trait which allows just that.

The current logic for the creation of the Scala class is moved to a dedicated class, `ScalaClassRenderer` and retrofitted to implement `BuildInfoRenderer`, set as the default renderer.

Existing users of sbt-buildinfo won't be affected by this PR, as the existing model or no pre existing key, only a new key is introduced to specify the renderer to use.

### CODE REVIEW

**Comment by eed3si9n** [comment]
This looks like a pretty big change. I'm ok with it, but can I make your a committer in case we have to maintain it going forward?

**Comment by pdalpra** [comment]
It mostly refactoring but it does introduce a few new mechanisms indeed.
And yes, go ahead, you can make me a committer :)

**Comment by eed3si9n** [comment]
Merged, and welcome to the team :)

**Comment by pdalpra** [comment]
Thanks :)

**Comment by pdalpra** [comment]
BTW, when you're going to cut a new release, do not hesitate to ping me here or on Twitter so that I can update the README to document that feature ;)

**Comment by eed3si9n** [comment]
I was gonna ask if you want to hand merge all the PRs you just broke :)

**Comment by eed3si9n** [comment]
I'm currently looking at #58

**Comment by pdalpra** [comment]
I'll take #61 !

**Comment by pdalpra** [comment]
Shall I merge them all ?

**Comment by pdalpra** [comment]
Working on #65 now

**Pull request merged**
