### PR TITLE
autoplugin enable by default

### PR DESCRIPTION
**Pull request by sokrahta**
This is to use plugin composition through 
`override def requires: Plugins = plugins.JvmPlugin && BuildInfoPlugin`

also enables in projects without explicitly calling `enablePlugins`

[Review on Reviewable](https://reviewable.io/reviews/sbt/sbt-buildinfo/55)

### CODE REVIEW

**Comment by sokrahta** [comment]
Hi @eed3si9n - nice plugin, I'd like to use it across my org's projects and include it in our dependency manager. Would love to have your eyes on this pull req. Thanks!

**Comment by eed3si9n** [comment]
I intentionally didn't enable it automatically because on multi-project builds I figured out don't want many build infos. If you're using `requires` and you make that a triggered plugin, wouldn't `BuildInfoPlugin` come in automatically?

**Comment by sokrahta** [comment]
Hmm well check this out and see if I'm doing something wrong. Our aggregating plugin triggers on all requirements, and we added `BuildInfoPlugin` to the dependencies like below.
```
object CoreSettingsPlugin extends AutoPlugin {
  override def trigger: PluginTrigger = allRequirements
  override def requires: Plugins = plugins.JvmPlugin && BuildInfoPlugin
```
Now sbt doesn't enable the `CoreSettingsPlugin` at all.

```
sbt (coresettings)> plugins
In file:/usr/local/src/socrata/socrata-sbt-plugins/src/sbt-test/PluginTests/CoreSettings/
	sbt.plugins.IvyPlugin: enabled in coresettings
	sbt.plugins.JvmPlugin: enabled in coresettings
	sbt.plugins.CorePlugin: enabled in coresettings
	sbt.plugins.JUnitXmlReportPlugin: enabled in coresettings
	com.socrata.sbtplugins.CloudbeesPlugin: enabled in coresettings
	com.socrata.sbtplugins.CoreSettingsPlugin
	com.socrata.sbtplugins.CoveragePlugin: enabled in coresettings
	com.socrata.sbtplugins.DependencyGraphPlugin: enabled in coresettings
	com.socrata.sbtplugins.MimaPlugin: enabled in coresettings
	com.socrata.sbtplugins.ReleasePlugin: enabled in coresettings
	com.socrata.sbtplugins.ScalaTestPlugin: enabled in coresettings
	com.socrata.sbtplugins.StylePlugin: enabled in coresettings
	com.socrata.sbtplugins.WebDavPlugin: enabled in coresettings
	scoverage.ScoverageSbtPlugin: enabled in coresettings
	sbtassembly.AssemblyPlugin: enabled in coresettings
	sbtbuildinfo.BuildInfoPlugin
```

**Comment by eed3si9n** [comment]
You're right. `allRequirements` is a trigger that fires when all required plugins are present, not the other way around. Maybe sbt needs another `PluginTrigger` that always fires.

**Comment by sokrahta** [comment]
Well it might be worth it still, but this is the way I've worked around this limitation - instead of using BuildInfo as an AutoPlugin, importing its projectSettings into scope directly.

```
object CoreSettingsPlugin extends AutoPlugin {
  override def trigger: PluginTrigger = allRequirements
  override def requires: Plugins = plugins.JvmPlugin

  override def projectSettings: Seq[Def.Setting[_]] = BuildInfoPlugin.projectSettings ++ Seq( ...
```

**Comment by sokrahta** [comment]
sbt-buildinfo will come in as a plugin to each project, but once it builds the managed code once sbt will leave it alone until next clean maybe?

**Comment by eed3si9n** [comment]
Currently `buildInfoPackage` defaults to "buildinfo":

https://github.com/sbt/sbt-buildinfo/blob/6f70fd55ee78807a68244acb8ec716541e07cad6/src/main/scala/sbtbuildinfo/BuildInfoPlugin.scala#L52:

```scala
buildInfoPackage := "buildinfo",
```

At it stands, it needs to be configured to something that won't collide. I want to make sure that the plugin's out-of-box experience is not broken by default. @jsuereth had the idea of using organization and normalizedName. I still feel like adding a new PluginTrigger is the way to go.

**Comment by sokrahta** [comment]
What kind of collision should I be looking for? I thought maybe a compile package/class name or assembly merge, but these are working fine.

**Pull request closed without merging**
