### PR TITLE
Added buildInfoUsePackageAsPath setting

### PR DESCRIPTION
**Pull request by peter-fu**
Added `buildInfoUsePackageAsPath` setting
- If true, the generated object is placed in the folder of the package
instead of "sbt-buildinfo".

The problem I'm trying to resolve:

Currently, if I set package name to `foo.bar.baz` it generates BuildInfo.scala at the following position, which can't be recognized ("BuildInfo is unresolved") in Scala IDE in a Java+Scala mixed project (I haven't tried pure Scala projects). The project can run without problem though (a Play 2.4 project).

`/target/src_managed/main/sbt-buildinfo/BuildInfo.scala`

If the generated scala file is located as following, the Scala IDE is satisfied.

`/target/src_managed/main/foo/bar/baz/BuildInfo.scala`

Solution: Move the generated scala file to proper folder according to the package name provided.

I understand that the problem is caused by something else such as Scala IDE, or Eclipse(JDT). However, this PR provides a workaround before the real problem is addressed. Play twirl and routes have already done that, so Scala IDE works with them well.

I don't use intellij, but I hope this PR can help with issue #56 and #69, too. The problems described in those issues look similar to mine.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks for the contribution.

**Comment by chrissom** [comment]
How can i get this patch?

**Comment by peter-fu** [comment]
Need to build this plugin from source against latest master branch and publish-local before new version is released.

**Comment by milessabin** [comment]
Looking forward to seeing this appear in a release.

**Comment by eed3si9n** [comment]
0.6.0 is out. sorry it looks so long -  http://notes.implicit.ly/post/139340558764/sbt-buildinfo-060

**Comment by michaelahlers** [comment]
@eed3si9n, huge thanks for fixing this!

**Pull request merged**
