### PR TITLE
Add option for Scala case class, and easy configuration of other renderers.

### PR DESCRIPTION
**Pull request by axos88**
One can now use
```
  buildInfoRenderFactory := ScalaCaseClassRenderer.apply,
```

To switch to another Renderer. Also added a Case Class renderer, which will create a case class AND an object that inherits the class. This makes it easy to use a jsonFormatter with the output.

### CODE REVIEW

**Comment by axos88** [comment]
Might be related: #95

**Comment by axos88** [comment]
Also: #47

**Comment by damdev** [comment]
Hi, there is any reason to not merge this PR? It will be pretty useful since the #95 issue it's fixed too

**Comment by eed3si9n** [comment]
The change looks nice. Sorry about the late response.

**Comment by axos88** [comment]
thx

**Comment by tobyweston** [comment]
👍 I was justing thinking the same when I saw this! thanks 😄

**Comment by marko-asplund** [comment]
I've added the below line in `build.sbt`
```
buildInfoRenderer := ScalaCaseObjectRenderer.apply
```

and get the following compile error:

```build.sbt:63: error: not found: value ScalaCaseObjectRenderer
buildInfoRenderer := ScalaCaseObjectRenderer.apply
                     ^
[error] Type error in expression```

What's the correct way to configure an alternative renderer?

**Comment by damdev** [comment]
@marko-asplund here https://github.com/sbt/sbt-buildinfo/blob/master/src/sbt-test/sbt-buildinfo/caseclassrenderer/build.sbt#L25 you have a example build with the ScalaCaseObjectRenderer configured. I think you are using the wrong setting key.

**Pull request merged**
