### PR TITLE
Add a Scala3Renderer

### PR DESCRIPTION
**Pull request by rreckel**
The toJson method does emit compilation warnings when compiled with scala3.
The import of Predef does not work neither.

This commit adds Scala3 Renderers to be used when compiling again scala3.
These are simple copy and paste implementations.....

If this pull request is accepted, it would be nice to change the default buildInfoRendererFactory to Scala3 implementations if the scalaVersion is >= 3 in BuilInfoPlugin.scala

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by mrdziuban** [comment]
@eed3si9n is there any chance you could release a new version that includes these changes? Thanks in advance!

**Comment by eed3si9n** [comment]
Wow it's been a while without a release. Thanks for the ping.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-buildinfo/releases/tag/v0.12.0

**Pull request merged**
