### PR TITLE
Make code generation -Yno-imports friendly

### PR DESCRIPTION
**Pull request by jedesah**
## Problem

Code generated by sbt-buildinfo cannot be compiled along with the `-Yno-imports` `scalac` flag

## Solution

Explicitly add `scala.Predef._` since we always generate code containing a reference to `String` and fully qualify any reference that is not a part of `scala.Predef._`.

### CODE REVIEW

**Comment by jedesah** [comment]
Fixes #80.

**Comment by jedesah** [comment]
@eed3si9n Wondering if you could have a quick look at this. I don't think it's a very long review and [Quasar](https://github.com/quasar-analytics/quasar) is blocked on a new release of `sbt-buildinfo` in order to upgrade to scala 2.11.8.

**Comment by eed3si9n** [comment]
LGTM

**Comment by eed3si9n** [comment]
http://notes.implicit.ly/post/140951454794/sbt-buildinfo-061

**Pull request merged**
