### PR TITLE
issue #146 implementation

### PR DESCRIPTION
**Pull request by pgrandjean**
Creating new PR to trigger new Travis build

### CODE REVIEW

**Comment by pgrandjean** [comment]
Rebased and now implementation is a little simpler than before.

**Comment by pgrandjean** [comment]
@eed3si9n may I kindly ask you for a feedback on this PR?

**Comment by eed3si9n** [comment]
Sorry I haven't been paying attention. Personally I don't understand the purpose of duplicating the build info, and I am against putting code duplication feature into my plugin.

**Comment by eed3si9n** [comment]
Why not just make an alias in a package object or something?

**Comment by pgrandjean** [comment]
OK, I understand. Closing this PR.

**Pull request closed without merging**
